CREATE TYPE "user_role" AS ENUM (
  'public',
  'farmer',
  'officer',
  'country_admin',
  'regional_admin',
  'super_admin'
);

CREATE TYPE "crop_category_type" AS ENUM (
  'Fruit',
  'Vegetable',
  'Root_Crop',
  'Grain',
  'Herb',
  'Spice'
);

CREATE TYPE "crop_status" AS ENUM (
  'planned',
  'planted',
  'growing',
  'ready_to_harvest',
  'harvested',
  'failed'
);

CREATE TYPE "crop_plan_status" AS ENUM (
  'draft',
  'active',
  'completed',
  'archived'
);

CREATE TYPE "plan_task_type" AS ENUM (
  'land_prep',
  'planting',
  'irrigation',
  'fertilizing',
  'pest_management',
  'harvest',
  'other'
);

CREATE TYPE "report_type" AS ENUM (
  'farmer_summary',
  'farm_report',
  'crop_inventory',
  'harvest_report',
  'crop_planning',
  'gis_summary',
  'country_summary'
);

CREATE TYPE "report_export_format" AS ENUM (
  'pdf',
  'csv'
);

CREATE TYPE "report_status" AS ENUM (
  'queued',
  'running',
  'complete',
  'failed'
);

CREATE TYPE "chat_room_type" AS ENUM (
  'direct',
  'crop',
  'district',
  'country'
);

CREATE TYPE "message_type" AS ENUM (
  'text',
  'image',
  'file'
);

CREATE TYPE "badge_rarity" AS ENUM (
  'common',
  'rare',
  'epic',
  'legendary'
);

CREATE TABLE "country_tenants" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) NOT NULL,
  "code" varchar(10) UNIQUE NOT NULL,
  "schema_name" varchar(80) UNIQUE NOT NULL,
  "region" varchar(120),
  "timezone" varchar(80),
  "is_active" boolean DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(150) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "first_name" varchar(100),
  "last_name" varchar(100),
  "password_hash" varchar(255),
  "is_active" boolean DEFAULT true,
  "is_staff" boolean DEFAULT false,
  "is_superuser" boolean DEFAULT false,
  "date_joined" timestamp,
  "last_login" timestamp
);

CREATE TABLE "user_profiles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "role" user_role NOT NULL DEFAULT 'public',
  "country_id" int,
  "district" varchar(120),
  "phone" varchar(50),
  "language" varchar(20) DEFAULT 'en',
  "points_balance" int DEFAULT 0,
  "is_mfa_enabled" boolean DEFAULT false,
  "consent_accepted_at" timestamp,
  "consent_version" varchar(50),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "role_definitions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" user_role UNIQUE NOT NULL,
  "label" varchar(120) NOT NULL,
  "rank" int NOT NULL,
  "description" text,
  "assignable" boolean DEFAULT true
);

CREATE TABLE "permissions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(120) UNIQUE NOT NULL,
  "label" varchar(160) NOT NULL,
  "description" text
);

CREATE TABLE "role_permissions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int NOT NULL,
  "permission_id" int NOT NULL,
  "allowed" boolean DEFAULT true
);

CREATE TABLE "audit_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "actor_id" int,
  "action" varchar(160) NOT NULL,
  "target_type" varchar(120),
  "target_id" varchar(120),
  "country_code" varchar(10),
  "metadata" jsonb,
  "ip_address" varchar(45),
  "created_at" timestamp NOT NULL
);

CREATE TABLE "crop_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) NOT NULL,
  "description" text,
  "icon" varchar(120),
  "sort_order" int DEFAULT 0
);

CREATE TABLE "crops" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" int NOT NULL,
  "name" varchar(160) NOT NULL,
  "scientific_name" varchar(180),
  "common_names" jsonb,
  "description" text,
  "origin" varchar(160),
  "nutritional_info" jsonb,
  "basic_uses" jsonb,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "crop_growing_guides" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "crop_id" int UNIQUE NOT NULL,
  "soil_types" jsonb,
  "water_requirement" varchar(80),
  "sunlight_requirement" varchar(80),
  "temperature_range" varchar(80),
  "land_area_per_unit" varchar(120),
  "spacing_requirements" varchar(160),
  "planting_depth" varchar(80),
  "fertilizer_recommendations" text,
  "pest_management" text,
  "disease_management" text,
  "companion_plants" jsonb,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "crop_seasonal_info" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "crop_id" int NOT NULL,
  "country_code" varchar(10) NOT NULL,
  "best_planting_months" jsonb,
  "harvest_months" jsonb,
  "growing_duration_days" int,
  "yield_per_hectare" varchar(120),
  "notes" text
);

CREATE TABLE "crop_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "crop_id" int NOT NULL,
  "image_url" text NOT NULL,
  "caption" varchar(255),
  "alt_text" varchar(255),
  "is_primary" boolean DEFAULT false,
  "sort_order" int DEFAULT 0
);

CREATE TABLE "crop_stages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "crop_id" int NOT NULL,
  "stage_name" varchar(120) NOT NULL,
  "stage_order" int NOT NULL,
  "description" text,
  "duration_days" int,
  "care_instructions" text,
  "image_url" text,
  "alt_text" varchar(255)
);

CREATE TABLE "farmer_profiles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "country_code" varchar(10) NOT NULL,
  "district" varchar(120) NOT NULL,
  "village" varchar(120),
  "farm_name" varchar(160),
  "total_land_hectares" decimal(12,2),
  "primary_soil_type" varchar(120),
  "farming_type" varchar(80),
  "years_experience" int,
  "phone" varchar(50),
  "profile_image" text,
  "bio" text,
  "is_verified" boolean DEFAULT false,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "farms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "farmer_id" int NOT NULL,
  "name" varchar(160) NOT NULL,
  "location_name" varchar(180),
  "latitude" decimal(10,7),
  "longitude" decimal(10,7),
  "area_hectares" decimal(12,2),
  "soil_type" varchar(120),
  "water_source" varchar(120),
  "elevation" decimal(10,2),
  "notes" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "farmer_crop_records" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "farmer_id" int NOT NULL,
  "farm_id" int NOT NULL,
  "crop_id" int NOT NULL,
  "planting_date" date NOT NULL,
  "expected_harvest_date" date,
  "actual_harvest_date" date,
  "land_area_used" decimal(12,2),
  "quantity_planted" decimal(12,2),
  "status" crop_status NOT NULL,
  "notes" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "harvest_records" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "crop_record_id" int NOT NULL,
  "harvest_date" date NOT NULL,
  "quantity_harvested" decimal(12,2),
  "unit" varchar(50),
  "quality_rating" int,
  "market_destination" varchar(180),
  "price_per_unit" decimal(12,2),
  "total_revenue" decimal(14,2),
  "notes" text
);

CREATE TABLE "crop_plans" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "farmer_id" int NOT NULL,
  "farm_id" int NOT NULL,
  "crop_id" int NOT NULL,
  "land_area" decimal(12,2),
  "soil_type" varchar(120),
  "water_availability" varchar(120),
  "generated_at" timestamp,
  "plan_data" jsonb,
  "confidence_score" decimal(5,2),
  "status" crop_plan_status DEFAULT 'draft',
  "estimated_harvest_date" date,
  "estimated_yield" varchar(120),
  "risk_level" varchar(80),
  "confidence_explanation" text,
  "confidence_warning" boolean DEFAULT false
);

CREATE TABLE "plan_tasks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "crop_plan_id" int NOT NULL,
  "week_number" int NOT NULL,
  "task_name" varchar(180) NOT NULL,
  "task_type" plan_task_type NOT NULL,
  "description" text,
  "priority" int,
  "is_completed" boolean DEFAULT false,
  "due_date" date
);

CREATE TABLE "plan_inputs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "crop_plan_id" int NOT NULL,
  "input_name" varchar(160) NOT NULL,
  "quantity" decimal(12,2),
  "unit" varchar(50),
  "estimated_cost" decimal(12,2),
  "week_number" int
);

CREATE TABLE "plan_milestones" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "crop_plan_id" int NOT NULL,
  "milestone_name" varchar(160) NOT NULL,
  "target_date" date,
  "is_reached" boolean DEFAULT false,
  "notes" text
);

CREATE TABLE "forum_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(160) NOT NULL,
  "description" text,
  "icon" varchar(120),
  "sort_order" int DEFAULT 0,
  "country_code" varchar(10)
);

CREATE TABLE "forum_threads" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" int NOT NULL,
  "author_id" int NOT NULL,
  "title" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "is_pinned" boolean DEFAULT false,
  "is_locked" boolean DEFAULT false,
  "view_count" int DEFAULT 0,
  "country_code" varchar(10),
  "crop_id" int,
  "tags" jsonb,
  "vote_score" int DEFAULT 0,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "forum_replies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "thread_id" int NOT NULL,
  "author_id" int NOT NULL,
  "content" text NOT NULL,
  "parent_reply_id" int,
  "is_official" boolean DEFAULT false,
  "vote_score" int DEFAULT 0,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "chat_rooms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(160) NOT NULL,
  "room_type" chat_room_type NOT NULL,
  "country_code" varchar(10),
  "crop_id" int,
  "created_at" timestamp
);

CREATE TABLE "chat_room_participants" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "room_id" int NOT NULL,
  "user_id" int NOT NULL,
  "joined_at" timestamp,
  "last_read_at" timestamp
);

CREATE TABLE "chat_messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "room_id" int NOT NULL,
  "sender_id" int NOT NULL,
  "content" text NOT NULL,
  "message_type" message_type DEFAULT 'text',
  "attachment_url" text,
  "created_at" timestamp,
  "is_read" boolean DEFAULT false
);

CREATE TABLE "chat_notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "message_id" int NOT NULL,
  "room_name" varchar(160),
  "sender_name" varchar(160),
  "message_content" text,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp
);

CREATE TABLE "point_transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "points" int NOT NULL,
  "action_type" varchar(120) NOT NULL,
  "description" text,
  "reference_id" varchar(120),
  "created_at" timestamp
);

CREATE TABLE "badges" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(160) NOT NULL,
  "description" text,
  "icon_url" text,
  "category" varchar(120),
  "points_required" int,
  "action_required" varchar(120),
  "rarity" badge_rarity DEFAULT 'common'
);

CREATE TABLE "user_badges" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "badge_id" int NOT NULL,
  "earned_at" timestamp
);

CREATE TABLE "achievements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "achievement_type" varchar(120) NOT NULL,
  "progress" int DEFAULT 0,
  "target" int NOT NULL,
  "completed_at" timestamp
);

CREATE TABLE "leaderboards" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country_code" varchar(10),
  "period" varchar(40) NOT NULL,
  "entries_json" jsonb,
  "generated_at" timestamp
);

CREATE TABLE "report_templates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "report_type" report_type NOT NULL,
  "title" varchar(180) NOT NULL,
  "description" text,
  "default_filters" jsonb,
  "favorite" boolean DEFAULT false,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "generated_reports" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "template_id" int,
  "requested_by_id" int,
  "country_code" varchar(10),
  "title" varchar(180) NOT NULL,
  "filters" jsonb,
  "export_format" report_export_format,
  "file_url" text,
  "status" report_status DEFAULT 'queued',
  "error_message" text,
  "created_at" timestamp,
  "completed_at" timestamp
);

CREATE TABLE "report_tables" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "generated_report_id" int NOT NULL,
  "title" varchar(180) NOT NULL,
  "columns" jsonb,
  "rows" jsonb
);

CREATE TABLE "analytics_cache" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cache_key" varchar(255) UNIQUE NOT NULL,
  "country_code" varchar(10),
  "filters" jsonb,
  "data" jsonb,
  "generated_at" timestamp,
  "expires_at" timestamp
);

CREATE UNIQUE INDEX ON "role_permissions" ("role_id", "permission_id");

CREATE UNIQUE INDEX ON "crop_seasonal_info" ("crop_id", "country_code");

CREATE UNIQUE INDEX ON "chat_room_participants" ("room_id", "user_id");

CREATE UNIQUE INDEX ON "user_badges" ("user_id", "badge_id");

COMMENT ON TABLE "country_tenants" IS 'Country-level tenant record. In implementation, each country can map to its own PostgreSQL schema.';

COMMENT ON TABLE "farms" IS 'PostGIS implementation may replace latitude/longitude with geometry(Point, 4326) and optional farm boundary polygon.';

ALTER TABLE "user_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_profiles" ADD FOREIGN KEY ("country_id") REFERENCES "country_tenants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("role_id") REFERENCES "role_definitions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("actor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crops" ADD FOREIGN KEY ("category_id") REFERENCES "crop_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crop_growing_guides" ADD FOREIGN KEY ("crop_id") REFERENCES "crops" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crop_seasonal_info" ADD FOREIGN KEY ("crop_id") REFERENCES "crops" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crop_images" ADD FOREIGN KEY ("crop_id") REFERENCES "crops" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crop_stages" ADD FOREIGN KEY ("crop_id") REFERENCES "crops" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "farmer_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "farms" ADD FOREIGN KEY ("farmer_id") REFERENCES "farmer_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "farmer_crop_records" ADD FOREIGN KEY ("farmer_id") REFERENCES "farmer_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "farmer_crop_records" ADD FOREIGN KEY ("farm_id") REFERENCES "farms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "farmer_crop_records" ADD FOREIGN KEY ("crop_id") REFERENCES "crops" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "harvest_records" ADD FOREIGN KEY ("crop_record_id") REFERENCES "farmer_crop_records" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crop_plans" ADD FOREIGN KEY ("farmer_id") REFERENCES "farmer_profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crop_plans" ADD FOREIGN KEY ("farm_id") REFERENCES "farms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crop_plans" ADD FOREIGN KEY ("crop_id") REFERENCES "crops" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plan_tasks" ADD FOREIGN KEY ("crop_plan_id") REFERENCES "crop_plans" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plan_inputs" ADD FOREIGN KEY ("crop_plan_id") REFERENCES "crop_plans" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plan_milestones" ADD FOREIGN KEY ("crop_plan_id") REFERENCES "crop_plans" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "forum_threads" ADD FOREIGN KEY ("category_id") REFERENCES "forum_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "forum_threads" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "forum_threads" ADD FOREIGN KEY ("crop_id") REFERENCES "crops" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "forum_replies" ADD FOREIGN KEY ("thread_id") REFERENCES "forum_threads" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "forum_replies" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "forum_replies" ADD FOREIGN KEY ("parent_reply_id") REFERENCES "forum_replies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_rooms" ADD FOREIGN KEY ("crop_id") REFERENCES "crops" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_room_participants" ADD FOREIGN KEY ("room_id") REFERENCES "chat_rooms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_room_participants" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("room_id") REFERENCES "chat_rooms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_notifications" ADD FOREIGN KEY ("message_id") REFERENCES "chat_messages" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "point_transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_badges" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_badges" ADD FOREIGN KEY ("badge_id") REFERENCES "badges" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "achievements" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "generated_reports" ADD FOREIGN KEY ("template_id") REFERENCES "report_templates" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "generated_reports" ADD FOREIGN KEY ("requested_by_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "report_tables" ADD FOREIGN KEY ("generated_report_id") REFERENCES "generated_reports" ("id") DEFERRABLE INITIALLY IMMEDIATE;
